# .github/workflows/check_allerte.yml

name: Controlla Allerte Meteo Marche

on:
  schedule:
    # Esegue ogni 30 minuti
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Scarica il codice del tuo repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Imposta l'ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installa le dipendenze Python direttamente
      # --- MODIFICA QUI ---
      # Non usiamo più requirements.txt, ma elenchiamo i pacchetti qui.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread requests pytz

      # 4. Crea il file credentials.json dal Secret di GitHub (INVARIATO)
      - name: Create Google Credentials File
        run: echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/credentials.json
        shell: bash

      # 5. Esegui lo script Python (INVARIATO)
      - name: Run Python script
        run: python estrai_allerte.py
