# Nome del workflow, aggiornato per il nuovo modello Thunder-ICON
name: Previsioni_Thunder_ECMWF_24h.py

on:
  # Permette di avviare il workflow manualmente dalla UI di GitHub.
  workflow_dispatch:

jobs:
  run-prediction:
    # Il tipo di runner su cui verrà eseguito il job.
    runs-on: ubuntu-latest
    
    # Variabili d'ambiente disponibili per tutti i passaggi del job.
    env:
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      PYTHONUNBUFFERED: 1

    # I passaggi (step) che compongono il job.
    steps:
    # 1. Fa il checkout del tuo codice dal repository.
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    # 2. Imposta l'ambiente Python.
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Assicurati che questa versione sia coerente con il tuo ambiente locale

    # 3. Debug: Mostra la struttura dei file per assicurarsi che requirementsgit.txt sia presente.
    - name: "Debug: List all files in the repository"
      run: ls -lR

    # 4. <<< INIZIO BLOCCO MODIFICATO >>>
    #    Installa le dipendenze Python direttamente dal file requirementsgit.txt.
    #    Questo garantisce che l'ambiente di GitHub sia una copia esatta del tuo.
    - name: Install dependencies from requirementsgit.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirementsgit.txt
    # <<< FINE BLOCCO MODIFICATO >>>

    # 5. Crea il file credentials.json dal secret di GitHub.
    - name: Create Google Credentials File
      run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json
      shell: bash

    # 6. Esegue il nuovo script Python di previsione.
    - name: Run Previsioni_Thunder_ECMWF_24h.py
      run: python Previsioni_Thunder_ECMWF_24h.py
