name: Scheduled Hydrological Simulation

# L'unica sezione "on" rimasta è workflow_dispatch, che abilita l'avvio manuale
on:
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    env:
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      GSHEET_DATA_SHEET_NAME: ${{ secrets.GSHEET_DATA_SHEET_NAME }}
      GSHEET_PREDICTIONS_SHEET_NAME: ${{ secrets.GSHEET_PREDICTIONS_SHEET_NAME }}
      PYTHONUNBUFFERED: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install pandas numpy scikit-learn joblib gspread google-auth pytz google-api-python-client

    - name: Create Google Credentials File
      run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json
      shell: bash

    - name: Run simulation script
      run: python run_simulation.py
