# Nome del workflow, visibile nella tab "Actions" di GitHub
name: Esegui Script Previsione Idrometrica

on:
  # Permette di lanciare il workflow manualmente dalla UI di GitHub
  workflow_dispatch:

  # Esegue il workflow a intervalli regolari
  schedule:
    - cron: '*/30 * * * *'

# Definizione dei task (job) da eseguire
jobs:
  run-prediction-script:
    # Il tipo di runner su cui verrà eseguito il job
    runs-on: ubuntu-latest
    env:
      # Passiamo solo l'ID del foglio come variabile d'ambiente
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      # Questo fa sì che l'output di Python appaia immediatamente
      PYTHONUNBUFFERED: 1

    # I passaggi (step) che compongono il job
    steps:
      # 1. Fa il checkout del tuo codice dal repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Imposta l'ambiente Python (usiamo 3.11 per coerenza)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      # 3. Installa le dipendenze Python necessarie dal file requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Crea il file credentials.json dal secret (METODO CORRETTO E FUNZIONANTE)
      - name: Create Google Credentials File
        run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json
        shell: bash

      # 5. Esegue lo script Python
      - name: Run prediction script
        run: python Previsione_idro.py
