name: Scheduled Hydrological Simulation

on:
  schedule:
    # Esegui ogni 30 minuti
    - cron: '*/30 * * * *'
  workflow_dispatch: # Permette l'esecuzione manuale da GitHub UI

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    env:
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      GSHEET_DATA_SHEET_NAME: ${{ secrets.GSHEET_DATA_SHEET_NAME }}
      GSHEET_PREDICTIONS_SHEET_NAME: ${{ secrets.GSHEET_PREDICTIONS_SHEET_NAME }}
      GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}
      PYTHONUNBUFFERED: 1 # Per output di log immediato

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # O la versione che usi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu # Per CPU, o versione CUDA se hai runner GPU
        pip install pandas numpy scikit-learn joblib gspread google-auth google-auth-oauthlib google-auth-httplib2 pytz
        # Aggiungi altre dipendenze se run_simulation.py ne richiede altre

    - name: Run simulation script
      run: python run_simulation.py

    - name: Commit and push changes (Opzionale, se vuoi tracciare i log o altri file generati)
      if: failure() == false # Esegui solo se lo script ha successo
      run: |
        # Questo è solo un esempio se volessi committare qualcosa,
        # per questo caso specifico di scrittura su GSheet non è necessario.
        # Se lo script generasse file di log che vuoi salvare nel repo:
        # git config --global user.name 'GitHub Actions Bot'
        # git config --global user.email 'actions@github.com'
        # git add . # Aggiunge tutti i file modificati/creati
        # git commit -m "CI: Run scheduled simulation and update logs" || echo "No changes to commit"
        # git push || echo "No changes to push"
      # Per questo use case, il commit non è strettamente necessario dato che i risultati vanno su GSheets.
      # Potrebbe essere utile se lo script producesse un file di log che vuoi versionare.
