name: Scheduled Hydrological Simulation

on:
  schedule:
    - cron: '*/30 * * * *' # Esegui ogni 30 minuti
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    env:
      # Non è più necessario GCP_SA_KEY_BASE64 qui se usiamo il file
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      GSHEET_DATA_SHEET_NAME: ${{ secrets.GSHEET_DATA_SHEET_NAME }}
      GSHEET_PREDICTIONS_SHEET_NAME: ${{ secrets.GSHEET_PREDICTIONS_SHEET_NAME }}
      PYTHONUNBUFFERED: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # O la versione Python che preferisci

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install pandas numpy scikit-learn joblib gspread google-auth pytz 
        # Rimosso oauth2client, google-auth-oauthlib, google-auth-httplib2 se non strettamente usate 
        # da gspread con service account file. google-auth dovrebbe bastare.
        # Verifica le dipendenze effettive di gspread con service account file.

    # --- MODIFICA: Crea credentials.json dal secret ---
    - name: Create Google Credentials File
      run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json
      shell: bash 
    # --- FINE MODIFICA ---

    - name: Run simulation script
      run: python run_simulation.py
