name: Scheduled Seq2Seq Hydrological Prediction

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    
    # Aggiungi qui i permessi necessari per l'autenticazione a Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      GSHEET_ID: ${{ secrets.GSHEET_ID }}
      PYTHONUNBUFFERED: 1
      # Aggiungi una variabile d'ambiente per il nome del bucket, per una facile manutenzione
      GCS_BUCKET_NAME: "NOME-DEL-TUO-BUCKET" # <-- SOSTITUISCI QUESTO VALORE!

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # NUOVO STEP: Autenticazione a Google Cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install pandas numpy scikit-learn joblib gspread google-auth-oauthlib pytz google-api-python-client google-cloud-storage

    # NUOVO STEP: Scarica i file del modello da Google Cloud Storage
    - name: Download Model Files from GCS
      run: |
        # Crea la cartella 'models' se non esiste
        mkdir -p models
        # Scarica tutti i file dalla cartella del modello nel bucket alla cartella locale 'models'
        gsutil -m cp -r "gs://${{ env.GCS_BUCKET_NAME }}/seq2seq_model/*" ./models/
        # Controlla che i file siano stati scaricati
        echo "File scaricati nella cartella models:"
        ls -l models

    # Questo passaggio non è più necessario se ti autentichi con l'action 'google-github-actions/auth'
    # - name: Create Google Credentials File
    #   run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json
    #   shell: bash
    
    - name: Run Seq2Seq prediction script
      run: python run_seq2seq_prediction.py
