name: Update Google Sheet

on:
  schedule:
    - cron: '30 * * * *'  # Run at 30 minutes past every hour
  workflow_dispatch:     # Allow manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Aggiunto oauth2client e urllib3 (usato nello script per i warning)
          pip install requests gspread oauth2client google-auth urllib3

      # Nuovo step: Crea il file credentials.json dal secret
      - name: Create credentials file
        run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json
        shell: bash # Assicura che echo funzioni come previsto

      - name: Run weather data extraction script
        run: python estrai_dati_meteo.py
        # Non è più necessario passare GCP_CREDENTIALS_JSON come env var
        # perché lo script ora legge da 'credentials.json'
        # env:
        #   GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
