name: Update Google Sheet

on:
  schedule:
    # - cron: '30 * * * *'  # Eseguito ai 30 minuti di ogni ora (Vecchio valore)
    - cron: '*/30 * * * *' # Eseguito ogni 30 minuti (es. 00:00, 00:30, 01:00, 01:30, ecc.)
  workflow_dispatch:     # Permette l'avvio manuale

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # *** AGGIUNTO pytz ALLA LISTA DELLE DIPENDENZE ***
          pip install requests gspread oauth2client google-auth urllib3 pytz

      # Nuovo step: Crea il file credentials.json dal secret
      # Assicurati che il nome del secret 'GCP_CREDENTIALS_JSON' sia corretto
      # nelle impostazioni del tuo repository GitHub.
      - name: Create credentials file
        run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json
        shell: bash # Assicura che echo funzioni come previsto

      - name: Run weather data extraction script
        # Assicurati che 'estrai_dati_meteo.py' sia nel percorso corretto
        run: python estrai_dati_meteo.py
        # Non è più necessario passare GCP_CREDENTIALS_JSON come env var
        # perché lo script ora legge da 'credentials.json' creato nello step precedente.
